[WIP] feat(cdn): add POST endpoint
godaddy/warehouse.ai pull request #107
Opened 2020-11-17 03:11 UTC by JacopoDaeli

2020-11-17 05:21 UTC, decompil3d requested changes

2020-11-17 05:21 UTC, decompil3d commented on lib/plugins/cdn.js
> +                metadata = JSON.parse(buffer.toString('utf8'));
Should we be more defensive to bad JSON here?

2020-11-17 05:21 UTC, decompil3d commented on lib/plugins/cdn.js
> +       * @param {number} [opts.exipration] Expiration timestamp
```suggestion
       * @param {number} [opts.expiration] Expiration timestamp
```

2020-11-17 05:21 UTC, decompil3d commented on lib/plugins/cdn.js
> +       * @returns {Promise<any>} Operation result
Can we use the type that `aws-sdk` exports for the `PutObject` call?

2020-11-17 05:21 UTC, decompil3d commented on lib/plugins/cdn.js
> +       * @returns {Promise<any>} Operation result
Same -- can we use a proper type here?

2020-11-17 06:29 UTC, JacopoDaeli commented
Probably in enough good shape now.

2020-11-18 05:45 UTC, JacopoDaeli commented on lib/plugins/cdn.js
> +              if (filename === '_metadata.json') {
No it's not a convention to mark `private/hidden`. It's just a convention for the metadata file.

2020-11-18 05:46 UTC, JacopoDaeli commented on lib/plugins/cdn.js
> +                  reject(err);
Stream should not be dropped since it's the http request itself. I'll remove the `on('entry')` listener to be extra safe.

2020-11-18 05:46 UTC, JacopoDaeli commented
@decompil3d looks good to you now?

2020-11-18 17:32 UTC, decompil3d approved these changes

2020-11-18 21:13 UTC, merged